#!/bin/sh

build_dir=$3

# Halcyon's incremental builds seem not to properly detect when yesod-static's
# Template Haskell cleverness needs to update, so let's assume the worst.
touch "$build_dir/Settings/StaticFiles.hs"
