Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  title: Hibi
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  is_heroku: true
  approot: "https://yesodoro-ngtest.herokuapp.com"
  <<: *defaults

Production:
  is_heroku: true
  approot: "https://yesodoro-ng.herokuapp.com"
  <<: *defaults
